apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-2
  namespace: default
  labels:
    app: zookeeper-controller-2
spec:
  replicas: 1
  selector:
    app: zookeeper-pod-2
  template:
    metadata:
      labels:
        app: zookeeper-pod-2
    spec:
      containers:
      - name: zookeeper-container-2
        image: mosuka/docker-zookeeper:release-3.4
        ports:
        - name: client
          containerPort: 2181
          protocol: TCP
        - name: peer
          containerPort: 2888
          protocol: TCP
        - name: election
          containerPort: 3888
          protocol: TCP
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-service-1
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-service-2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-service-3
