apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-1
  namespace: default
  labels:
    app: zookeeper-service-1
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: peer
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: election
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper-pod-1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-2
  namespace: default
  labels:
    app: zookeeper-service-2
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: peer
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: election
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper-pod-2
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-3
  namespace: default
  labels:
    app: zookeeper-service-3
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: peer
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: election
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper-pod-3
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-1
  namespace: default
  labels:
    app: zookeeper-controller-1
spec:
  replicas: 1
  selector:
    app: zookeeper-pod-1
  template:
    metadata:
      labels:
        app: zookeeper-pod-1
    spec:
      containers:
      - name: zookeeper-container-1
        image: mosuka/docker-zookeeper:release-3.4
        ports:
        - name: client
          containerPort: 2181
          protocol: TCP
        - name: peer
          containerPort: 2888
          protocol: TCP
        - name: election
          containerPort: 3888
          protocol: TCP
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-service-1
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-service-2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-service-3
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-2
  namespace: default
  labels:
    app: zookeeper-controller-2
spec:
  replicas: 1
  selector:
    app: zookeeper-pod-2
  template:
    metadata:
      labels:
        app: zookeeper-pod-2
    spec:
      containers:
      - name: zookeeper-container-2
        image: mosuka/docker-zookeeper:release-3.4
        ports:
        - name: client
          containerPort: 2181
          protocol: TCP
        - name: peer
          containerPort: 2888
          protocol: TCP
        - name: election
          containerPort: 3888
          protocol: TCP
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-service-1
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-service-2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-service-3
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-3
  namespace: default
  labels:
    app: zookeeper-controller-3
spec:
  replicas: 1
  selector:
    app: zookeeper-pod-3
  template:
    metadata:
      labels:
        app: zookeeper-pod-3
    spec:
      containers:
      #- name: zoo3
      - name: zookeeper-container-3
        image: mosuka/docker-zookeeper:release-3.4
        ports:
        - name: client
          containerPort: 2181
          protocol: TCP
        - name: peer
          containerPort: 2888
          protocol: TCP
        - name: election
          containerPort: 3888
          protocol: TCP
        env:
        - name: ZOOKEEPER_ID
          value: "3"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-service-1
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-service-2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-service-3
