apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-3
  namespace: default
  labels:
    app: zookeeper-service-3
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: peer
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: election
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper-pod-3
