apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: default
  labels:
    app: zookeeper-service
spec:
  type: NodePort
  selector:
    app: zookeeper-pod
  ports:
    - name: client
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: peer
      port: 2888
      targetPort: 2888
      protocol: TCP
    - name: election
      port: 3888
      targetPort: 3888
      protocol: TCP
