apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  ports:
  - name: zookeeper-client-port
    port: 2181
    protocol: TCP
  - name: zookeeper-peer-port
    port: 2888
    protocol: TCP
  - name: zookeeper-election-port
    port: 3888
    protocol: TCP
  type: NodePort
  selector:
    app: zookeeper-pod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-replica
  labels:
    app: zookeeper-replica
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper-pod
    spec:
      containers:
      - name: zookeeper-container
        image: mosuka/docker-zookeeper:latest
        ports:
        - name: "zookeeper-client-port"
          containerPort: 2181
          protocol: TCP
        - name: "zookeeper-peer-port"
          containerPort: 2888
          protocol: TCP
        - name: "zookeeper-election-port"
          containerPort: 3888
          protocol: TCP

