apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: default
  labels:
    app: zookeeper-service
spec:
  type: NodePort
  selector:
    app: zookeeper-pod
  ports:
    - name: client-port
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: peer-port
      port: 2888
      targetPort: 2888
      protocol: TCP
    - name: election-port
      port: 3888
      targetPort: 3888
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller
  namespace: default
  labels:
    app: zookeeper-controller
spec:
  replicas: 3
  selector:
    app: zookeeper-pod
  template:
    metadata:
      labels:
        app: zookeeper-pod
    spec:
      containers:
        - name: zookeeper-container
          image: mosuka/docker-zookeeper:release-3.5
          #command:
          #  - "/opt/zookeeper/bin/zkEnsemble.sh"
          #  - "start"
          #  - "--foreground"
          #  - "--seed=$(echo $(curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].addresses[].ip' | sed -e 's/[^0-9]*\\([0-9.]*\\)[^0-9]*.*/\\1/g' | grep -v -e \"^$POD_IP$\" | head -1):$(curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].ports[]' | jq 'select(.name == \"client-port\").port'))"
          command:
            - "/bin/sh"
            - "-c"
          args:
            #- "sleep 3600"
            #- "sleep 5 ; /opt/zookeeper/bin/zkEnsemble.sh start --foreground --seed=$(echo $(curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].addresses[].ip' | sed -e 's/[^0-9]*\\([0-9.]*\\)[^0-9]*.*/\\1/g' | grep -v -e \"^$POD_IP$\" | head -1):$(curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].ports[]' | jq 'select(.name == \"client-port\").port'))"
            - "sleep 60 ; echo $POD_IP > /tmp/node_ip ; curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].addresses[].ip' | sed -e 's/[^0-9]*\\([0-9.]*\\)[^0-9]*.*/\\1/g' | grep -v -e \"^$POD_IP$\" | head -1 > /tmp/seed_node_ip ; curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].ports[]' | jq 'select(.name == \"client-port\").port' > /tmp/seed_node_port ; /opt/zookeeper/bin/zkEnsemble.sh start --foreground --seed=$(cat /tmp/seed_node_ip):$(cat /tmp/seed_node_port)"
            #- "sleep 5 ; docker-run.sh --seed=$(echo $(curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].addresses[].ip' | sed -e 's/[^0-9]*\\([0-9.]*\\)[^0-9]*.*/\\1/g' | grep -v -e \"^$POD_IP$\" | head -1):$(curl --cacert $CRT_PATH -H \"Authorization:Bearer $(cat $TOKEN_PATH)\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/$API_PATH | jq '.subsets[].ports[]' | jq 'select(.name == \"client-port\").port'))"
          env:
            - name: CRT_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - name: TOKEN_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: API_PATH
              value: api/v1/namespaces/default/endpoints/zookeeper-service
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          #  - name: POD_PREFIX
          #    value: zookeeper-controller
          #  - name: POD_NAME
          #    valueFrom:
          #      fieldRef:
          #        fieldPath: metadata.name
          #  - name: POD_NAMESPACE
          #    valueFrom:
          #      fieldRef:
          #        fieldPath: metadata.namespace
          lifecycle:
            #postStart:
            #  exec:
            #    command:
            #    - "sh"
            #    - "-c"
            #    - "echo START >> /tmp/pod_status"
            preStop:
              exec:
                #command: ["/opt/zookeeper/bin/zkEnsemble.sh", "stop"]
                #command:
                #  - "/opt/zookeeper/bin/zkEnsemble.sh"
                #  - "stop"
                #  - "--ip=$POD_IP"
                #  - "--clientport=2181"
                #command:
                #  - "/bin/sh"
                #  - "-c"
                #args:
                #  - "/opt/zookeeper/bin/zkEnsemble.sh stop --ip=$POD_IP --clientport=2181"
                command:
                  - "/bin/sh"
                  - "-c"
                  - "\"/opt/zookeeper/bin/zkEnsemble.sh stop --ip=$(cat /tmp/node_ip) --clientport=2181\""
          ports:
            - name: client-port
              containerPort: 2181
              protocol: TCP
            - name: peer-port
              containerPort: 2888
              protocol: TCP
            - name: election-port
              containerPort: 3888
              protocol: TCP